// INDEX FRONTEND
import { useEffect, useState } from "react";
import axios from "axios";

export default function Home() {
  const [users, setUsers] = useState([]);
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");

  //update
  const [editingId, setEditingId] = useState(null);
  const [editName, setEditName] = useState("");
  const [editEmail, setEditEmail] = useState("");

  //find
  const [searchId, setSearchId] = useState("");
  const [foundUser, setFoundUser] = useState(null);


  useEffect(() => {
    axios.get("http://localhost:4000/users").then(res => setUsers(res.data));
    fetchUserById();
  }, []);

  // ADD USUARIO
  const addUser = async () => {
    const res = await axios.post("http://localhost:4000/users", { name, email });
    setUsers([...users, res.data]);
    setName("");
    setEmail("");
  };

  // DELETE USUARIO
  const deleteUser = async (id) => {
    const res = await axios.delete(`http://localhost:4000/users/${id}`);
    alert(res.data.message);
    setUsers(users.filter(u => u._id !== id));
  };

  // ATUALIZA USUARIO
  const updateUser = async () => {
    if (!editingId) return;
    const res = await axios.put(`http://localhost:4000/users/${editingId}`, {
      name: editName,
      email: editEmail
    });
    alert(res.data.message);

    setUsers(users.map(u => u._id === editingId ? res.data.user : u));
    setEditingId(null);
    setEditName("");
    setEditEmail("");
  };

  // BUSCA USUARIO PELO ID
  const fetchUserById = async () => {
    if (!searchId) return;
    try {
      const res = await axios.get(`http://localhost:4000/users/${searchId}`);
      setFoundUser(res.data.user);
    } catch (err) {
      console.error(err);
      setFoundUser(null);
      alert("Usuário não encontrado");
    }
  };


  return (
    <div style={{ padding: 20 }}>
      <h1>Usuários</h1>

      <div style={{ margin: "20px 0" }}>
        <input placeholder="Nome" value={name} onChange={(e) => setName(e.target.value)} />
        <input placeholder="Email" value={email} onChange={(e) => setEmail(e.target.value)} />
        <button onClick={addUser}>Adicionar</button>
      </div>

      <ul>
        {users.map(u => (
          <li key={u._id}>
            {u.name} - {u.email}
            <button onClick={() => deleteUser(u._id)}>Deletar</button>
            <button onClick={() => {
              setEditingId(u._id);
              setEditName(u.name);
              setEditEmail(u.email);
            }}>Editar</button>
          </li>
        ))}
      </ul>

      {editingId && (
        <div style={{ marginTop: 20 }}>
          <h3>Editando Usuário</h3>
          <input value={editName} onChange={(e) => setEditName(e.target.value)} />
          <input value={editEmail} onChange={(e) => setEditEmail(e.target.value)} />
          <button onClick={updateUser}>Salvar</button>
          <button onClick={() => setEditingId(null)}>Cancelar</button>
        </div>
      )}

      <hr style={{ margin: "20px 0" }}/>
    <h2>Buscar Usuário</h2>
      <input
        type="text"
        placeholder="Digite o ID"
        value={searchId}
        onChange={(e) => setSearchId(e.target.value)}
      />
      <button onClick={fetchUserById}>Buscar</button>

      {foundUser && (
        <div>
          <h3>Usuário encontrado:</h3>
          <p>Nome: {foundUser.name}</p>
          <p>Email: {foundUser.email}</p>
        </div>
      )}

    </div>

  );
}



/*
import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />
          <ol>
            <li>
              Get started by editing <code>pages/index.js</code>.
            </li>
            <li>Save and see your changes instantly.</li>
          </ol>

          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                className={styles.logo}
                src="/vercel.svg"
                alt="Vercel logomark"
                width={20}
                height={20}
              />
              Deploy now
            </a>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.secondary}
            >
              Read our docs
            </a>
          </div>
        </main>
        <footer className={styles.footer}>
          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/file.svg"
              alt="File icon"
              width={16}
              height={16}
            />
            Learn
          </a>
          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/window.svg"
              alt="Window icon"
              width={16}
              height={16}
            />
            Examples
          </a>
          <a
            href="https://nextjs.org?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/globe.svg"
              alt="Globe icon"
              width={16}
              height={16}
            />
            Go to nextjs.org →
          </a>
        </footer>
      </div>
    </>
  );
}
*/